# 기본 테이블에서 열 불러오기
SELECT ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS

#역순 정렬
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC

#특정 조건의 데이터 찾기 (1) ~ 동일
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION LIKE 'Sick'

#특정조건의 데이터 찾기 (2) ~ 부정
SELECT ANIMAl_ID, NAME
FROM ANIMAL_INS
where INTAKE_CONDITION != 'Aged'

#특정 열 불러오기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS

#여러기준으로 불러오기
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME asc, DATETIME DESC

#상위 n개 레코드
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
limit 1

