# GROUP_BY (1)
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE)
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE ASC

# GROUP_BY (2) + HAVING 절
SELECT NAME, COUNT(*) as 'COUNT'
FROM ANIMAL_INS
WHERE NAME is not NULL
GROUP BY NAME
HAVING count >1
ORDER BY NAME

# GROUP_BY + BETWEEN 절
SELECT HOUR(DATETIME) AS "HOUR", COUNT(*) AS "COUNT"
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME) ASC

# GROUP_BY + 반복문(WITH RECURSIVE)
WITH RECURSIVE TIME as (
    SELECT 0 AS h
    UNION ALL
    select h+1 from TIME where h<23)

select h,COUNT(HOUR(DATETIME)) as 'cOUNT'
FROM TIME LEFT OUTER JOIN ANIMAL_OUTS
ON (h = (HOUR(DATETIME)))
GROUP BY h
